sudo: required

services:
  - docker

language: node_js

os:
  - linux

before_script:
  - docker pull appcelerator/etcd:3.1.9
  - ./start-etcd.sh
  - docker ps

script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls

after_script:
  - ./kill-etcd.sh

node_js:
  - "6"
  - "8"
