version: "3.3"
services:
  kickerd-etcd:
    image: appcelerator/etcd:3.1.9
    ports:
      - "12379:2379"
      - "12380:2380"
  etcdeck:
    image: arobson/etcdeck:latest
    depends_on:
      - etcd
    ports:
      - 8018:8018
    environment:
      - ETCD=http://kickerd-etcd:12379
      - ETCD_URL=http://kickerd-etcd:12379
  app:
    build:
      context: ./
      dockerfile: Dockerfile.demo
    depends_on:
      - etcd
    ports:
      - 8008:8008
