version: "3.3"
services:
  etcd:
    image: appcelerator/etcd:3.1.9
    ports:
      - "2379:2379"
      - "2380:2380"
  etcdeck:
    image: arobson/etcdeck:latest
    depends_on:
      - etcd
    ports:
      - 8018:8018
    environment:
      - ETCD=http://etcd:2379
      - ETCD_URL=http://etcd:2379
  app:
    build:
      context: ./
      dockerfile: Dockerfile.demo
    depends_on:
      - etcd
    ports:
      - 8008:8008
