name = "http"
start = "node ./index.js"

[environment]
  TITLE = "{{site-title}}"
  PORT = "{{site-port}}"
  MOTD = "{{site-motd}}"

[default]
  TITLE = "Demo"
  PORT = 8008
  MOTD = "Ohhai, it's a thing"

[file]
  "./app.cfg" = "{{site-config}}"
